query listCloudAccounts {
    cloudAccounts {
        edges {
            node {
                awsAccountId
                id
                isRealtimeScanningEnabled
                label
            }
        }
    }
}