mutation updateCloudAccount ($input: UpdateCloudAccountInput!) {
    updateCloudAccount(input: $input) {
        cloudAccount {
            awsAccountId
            awsRegionIgnoreList
            awsScanConfig {
            auditRole
            }
            awsStackName
            createdAt
            createdBy {
                ... on User {
                    id
                }
                ... on APIToken {
                    id
                }
            }
            id
            isEditable
            isRealtimeScanningEnabled
            label
            lastModifiedAt
            resourceRegexIgnoreList
            resourceTypeIgnoreList
        }
    }
}
