mutation UpdateAlertAssigneeByEmail ($input: UpdateAlertsAssigneeByEmailInput!) {
    updateAlertsAssigneeByEmail (input: $input) {
        alerts {
            id
            assignee {
                email
                givenName
                familyName
                id
            }
        }
    }
}